<script setup>
// setTimeout(val=>{
//   console.log(ImagePreview);
//   // ImagePreview(['https://img.yzcdn.cn/vant/apple-1.jpg']);
// },5000)
import getHomeDatas from "./network/home.js";
import { onMounted, ref, reactive } from "vue";
import mapImg from "@/assets/map1.png";
import RightContent from "@/components/RightContent.vue";
let markerClusterer = ref(null);
let infoObj = reactive({ data: [] });
let homeData = ref(null);
const rightRef = ref(null);
let changePro = ref("");
// console.log(rightDatas);
let maps;
const expandContent = (val) => {
  if (val && Object.keys(val).length > 0) {
    let map = maps();
    var point = new BMap.Point(val.lng, val.lat);
    var marker = new BMap.Marker(point); // 创建标注
    map.addOverlay(marker);
    map.centerAndZoom(point, 15);
    return;
  }
  let map = maps();
  var point = new BMap.Point(116.404, 39.915);
  map.centerAndZoom(point, 5);
  map.clearOverlays();
};

const changeMap = (pro) => {
  let selectPro = arrs.find((val) => {
    if (pro.indexOf(val.attrs.name) >= 0) return true;
    return false;
  });
  selectPro.markerMethod();
};
let num = 0;
// 对请求数据处理格式
let proobj = {};
let arrs = [
  {
    attrs: {
      name: "西藏",
      num: 0,
      apiNum: 540000,
    },
    coords: [88.40331420290153, 31.27613542572102],
  },
  {
    attrs: {
      name: "新疆",
      num: 0,
      apiNum: 650000,
    },
    coords: [85.23897914567358, 40.983162925138906],
  },
  {
    attrs: {
      name: "青海",
      num: 0,
      apiNum: 630000,
    },
    coords: [96.13017887752788, 35.833468131842004],
  },
  {
    attrs: {
      name: "四川",
      num: 0,
      apiNum: 510000,
    },
    coords: [102.82679492887074, 30.38705449265531],
  },
  {
    //  ['118.20693509074607,43.97828894758099', '128.73018887603038,46.626237249310776', '126.89045920127856,43.17577398845946', '122.62228633338971,41.26141060524387']
    attrs: {
      name: "内蒙古",
      num: 0,
      apiNum: 150000,
    },
    coords: [118.20693509074607, 43.97828894758099],
  },
  {
    attrs: {
      name: "黑龙江",
      num: 0,
      apiNum: 230000,
    },
    coords: [128.73018887603038, 46.626237249310776],
  },
  {
    attrs: {
      name: "吉林",
      num: 0,
      apiNum: 220000,
    },
    coords: [126.59610245176899, 43.01397869177952],
  },
  {
    attrs: {
      name: "辽宁",
      num: 0,
      apiNum: 210000,
    },
    coords: [122.62228633338971, 41.26141060524387],
  },
  {
    //    ) ['116.36720540631123,40.36683818997784', '117.32386484221735,38.541371157860304', '114.96901084614073,36.96381629084649', '118.57488102763304,36.311425068715415', '119.23718371402958,33.76974693229767']
    attrs: {
      name: "北京",
      num: 0,
      apiNum: 110000,
    },
    coords: [116.36720540631123, 40.36683818997784],
  },
  {
    attrs: {
      name: "天津",
      num: 0,
      apiNum: 120000,
    },
    coords: [117.32386484221735, 38.541371157860304],
  },
  {
    attrs: {
      name: "河北",
      num: 0,
      apiNum: 130000,
    },
    coords: [114.96901084614073, 36.96381629084649],
  },
  {
    attrs: {
      name: "山东",
      num: 0,
      apiNum: 370000,
    },
    coords: [118.57488102763304, 36.311425068715415],
  },
  {
    attrs: {
      name: "江苏",
      num: 0,
      apiNum: 320000,
    },
    coords: [119.23718371402958, 33.76974693229767],
  },

  {
    attrs: {
      name: "宁夏",
      num: 0,
      apiNum: 640000,
    },
    coords: [106.17510295454217, 37.31731197533817],
  },
  {
    attrs: {
      name: "山西",
      num: 0,
      apiNum: 140000,
    },
    coords: [111.7678811952241, 37.19966523899118],
  },
  {
    attrs: {
      name: "河南",
      num: 0,
      apiNum: 410000,
    },
    coords: [112.87171900588501, 33.76974693229767],
  },
  {
    attrs: {
      name: "重庆",
      num: 0,
      apiNum: 500000,
    },
    coords: [106.93399143695966, 29.64252635580032],
  },
  {
    attrs: {
      name: "湖北",
      num: 3,
      apiNum: 420000,
    },
    coords: [112.43018388162065, 31.02296196655853],
  },
  {
    attrs: {
      //     ['104.24338678588558,34.86880270715298', '108.51155965377443,33.64673567985549', '106.58653247799029,26.94946094502287']
      name: "甘肃",
      num: 0,
      apiNum: 620000,
    },
    coords: [104.24338678588558, 34.86880270715298],
  },
  {
    attrs: {
      name: "陕西",
      num: 0,
      apiNum: 610000,
    },
    coords: [108.51155965377443, 33.64673567985549],
  },
  {
    attrs: {
      name: "贵州",
      num: 0,
      apiNum: 520000,
    },
    coords: [106.58653247799029, 26.94946094502287],
  },
  {
    //    ['111.51031902547965,27.605379141146173', '119.97307557108445,28.908584731901524', '121.81280527223838,31.27613542572102', '113.7179946460722,23.738305667193558']
    attrs: {
      name: "湖南",
      num: 0,
      apiNum: 430000,
    },
    coords: [111.51031902547965, 27.605379141146173],
  },
  {
    attrs: {
      name: "浙江",
      num: 0,
      apiNum: 330000,
    },
    coords: [119.97307557108445, 28.908584731901524],
  },
  {
    attrs: {
      name: "上海",
      num: 0,
      apiNum: 310000,
    },
    coords: [121.81280527223838, 31.27613542572102],
  },
  {
    attrs: {
      name: "广东",
      num: 0,
      apiNum: 440000,
    },
    coords: [113.7179946460722, 23.738305667193558],
  },

  {
    attrs: {
      name: "福建",
      num: 4,
      apiNum: 350000,
    },
    coords: [117.97300003161725, 26.129814585743876],
  },

  {
    attrs: {
      name: "安徽",
      num: 2,
      apiNum: 340000,
    },
    coords: [116.91055615491452, 31.867923507180713],
  },

  // {
  //   attrs: {
  //     name: "广西",
  //     num: 0,
  //     apiNum: 0,
  //   },
  //   coords: [115.29159401743921, 27.696634980588026],
  // },
  {
    attrs: {
      name: "广西",
      num: 0,
      apiNum: 450000,
    },
    coords: [108.8893347177208, 23.56153347202005],
  },
  {
    attrs: {
      name: "台湾",
      num: 0,
      apiNum: 710000,
    },
    coords: [120.95796144362677, 23.697143286454434],
  },
  {
    attrs: {
      name: "香港",
      num: 0,
      apiNum: 810000,
    },
    coords: [114.22392030912467, 22.299306812898774],
  },
  {
    attrs: {
      name: "江西",
      num: 0,
      apiNum: 360000,
    },
    coords: [115.5209297362228, 28.063329789924733],
  },
  {
    attrs: {
      name: "云南",
      num: 0,
      apiNum: 530000,
    },
    coords: [101.5389841391366, 24.58234442249256],
  },
];
function randomColor() {
  var arr = ["blue", "red"];
  //   color += parseInt(Math.random() * 16).toString(16);
  if (num == 2) num = 0;
  return arr[num++];
}
let data;
// let data = [
//   // {
//   //   mdid: 6701,
//   //   khmc: "松原市欧亚购物中心",
//   //   jmpro: "吉林省",
//   //   sskhdm: "JL0003",
//   //   lng: 124.807305,
//   //   wdfl: "lh2",
//   //   sskhfl: "xf",
//   //   khid: 15781,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xz",
//   //   mddm: "jesy08",
//   //   khdm: "jesy08",
//   //   wdmc: "领航二部",
//   //   sskhmc: "2X·吉林盛凯特公司(混合)",
//   //   khflmc: "主品牌直营店",
//   //   id: 17350,
//   //   sskhid: 949,
//   //   jmcity: "松原市",
//   //   mdmc: "松原市欧亚购物中心",
//   //   lat: 45.148677,
//   //   jmarea: "宁江区",
//   // },
//   // {
//   //   mdid: 11154,
//   //   khmc: "抚州市硕果时代广场店",
//   //   jmpro: "江西省",
//   //   sskhdm: "JX0067",
//   //   lng: 116.364183,
//   //   wdfl: "lh1",
//   //   sskhfl: "xf",
//   //   khid: 22154,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xz",
//   //   mddm: "gyfz06",
//   //   khdm: "gyfz06",
//   //   wdmc: "领航一部",
//   //   sskhmc: "1X·江西睿毅公司(混合)",
//   //   khflmc: "主品牌直营店",
//   //   id: 17352,
//   //   sskhid: 15110,
//   //   jmcity: "抚州市",
//   //   mdmc: "抚州市硕果时代广场店",
//   //   lat: 27.954473,
//   //   jmarea: "临川区",
//   // },
//   // {
//   //   mdid: 11171,
//   //   khmc: "秦皇岛市昌黎县信发商厦",
//   //   jmpro: "河北省",
//   //   sskhdm: "BJ0069",
//   //   lng: 119.166475,
//   //   wdfl: "lh6",
//   //   sskhfl: "xf",
//   //   khid: 22178,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xj",
//   //   mddm: "jscl02",
//   //   khdm: "jscl02",
//   //   wdmc: "领航三部",
//   //   sskhmc: "3X·北京睿尚公司(混合)",
//   //   khflmc: "主品牌加盟店",
//   //   id: 17353,
//   //   sskhid: 15108,
//   //   jmcity: "秦皇岛市",
//   //   mdmc: "秦皇岛市昌黎县信发商厦",
//   //   lat: 39.719641,
//   //   jmarea: "昌黎县",
//   // },
//   {
//     mdid: 11255,
//     khmc: "神木市东兴街55号店",
//     jmpro: "陕西省",
//     sskhdm: "NM0009",
//     lng: 110.503771,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22314,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "sasm09",
//     khdm: "sasm09",
//     wdmc: "领航一部",
//     sskhmc: "1J·内蒙古优尚公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17354,
//     sskhid: 17208,
//     jmcity: "榆林市",
//     mdmc: "神木市东兴街55号店",
//     lat: 38.821956,
//     jmarea: "神木市",
//   },
//   // {
//   //   mdid: 11157,
//   //   khmc: "宜春市万达室内步行街店",
//   //   jmpro: "江西省",
//   //   sskhdm: "JX0068",
//   //   lng: 114.425038,
//   //   wdfl: "lh1",
//   //   sskhfl: "xf",
//   //   khid: 22160,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xz",
//   //   mddm: "gzyc11",
//   //   khdm: "gzyc11",
//   //   wdmc: "领航一部",
//   //   sskhmc: "1X·江西臻道公司(混合)",
//   //   khflmc: "主品牌直营店",
//   //   id: 17355,
//   //   sskhid: 15109,
//   //   jmcity: "宜春市",
//   //   mdmc: "宜春市万达室内步行街店",
//   //   lat: 27.805562,
//   //   jmarea: "袁州区",
//   // },
//   {
//     mdid: 11158,
//     khmc: "石门县步行街店",
//     jmpro: "湖南省",
//     sskhdm: "HN0107",
//     lng: 111.376669,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22161,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "xxsm04",
//     khdm: "xxsm04",
//     wdmc: "领航二部",
//     sskhmc: "2J·湖南佳昂公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17356,
//     sskhid: 20555,
//     jmcity: "常德市",
//     mdmc: "石门县步行街店",
//     lat: 29.581463,
//     jmarea: "石门县",
//   },
//   {
//     mdid: 7985,
//     khmc: "滁州市南谯路白云商场",
//     jmpro: "安徽省",
//     sskhdm: "AH0011",
//     lng: 118.310829,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 17865,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ancz01",
//     khdm: "ancz01",
//     wdmc: "领航二部",
//     sskhmc: "2J·安徽郎胜公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17357,
//     sskhid: 83,
//     jmcity: "滁州市",
//     mdmc: "滁州市南谯路白云商场",
//     lat: 32.305851,
//     jmarea: "琅琊区",
//   },
//   {
//     mdid: 11198,
//     khmc: "汕头市龙湖区万象城店",
//     jmpro: "广东省",
//     sskhdm: "GD0115",
//     lng: 116.717438,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 22224,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ygst02",
//     khdm: "ygst02",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东粤东(直营)",
//     khflmc: "主品牌直营店",
//     id: 17358,
//     sskhid: 21348,
//     jmcity: "汕头市",
//     mdmc: "汕头市龙湖区万象城店",
//     lat: 23.362961,
//     jmarea: "龙湖区",
//   },
//   {
//     mdid: 11169,
//     khmc: "湖南长沙市洋湖天街店",
//     jmpro: "湖南省",
//     sskhdm: "HN0105",
//     lng: 112.946641,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22173,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "xhcs06",
//     khdm: "xhcs06",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·长沙销售公司",
//     khflmc: "轻商务直营店",
//     id: 17359,
//     sskhid: 20261,
//     jmcity: "长沙市",
//     mdmc: "湖南长沙市洋湖天街店",
//     lat: 28.129447,
//     jmarea: "岳麓区",
//   },
//   {
//     mdid: 11168,
//     khmc: "贵阳市花溪区龙湾万达室内步行街店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0142",
//     lng: 106.701558,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22172,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "qlgy52",
//     khdm: "qlgy52",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州贵阳销售公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17341,
//     sskhid: 22018,
//     jmcity: "贵阳市",
//     mdmc: "贵阳市花溪区龙湾万达室内步行街店",
//     lat: 26.52298,
//     jmarea: "花溪区",
//   },
//   // {
//   //   mdid: 8201,
//   //   khmc: "北京市海淀区翠微印象城店",
//   //   jmpro: "北京市",
//   //   sskhdm: "BJ0090",
//   //   lng: 116.303528,
//   //   wdfl: "xk",
//   //   sskhfl: "xk",
//   //   khid: 18196,
//   //   sskhflmc: "轻商务管理中心",
//   //   xh: 1,
//   //   khfl: "xm",
//   //   mddm: "jzbj03",
//   //   khdm: "jzbj03",
//   //   wdmc: "轻商务管理中心",
//   //   sskhmc: "X·北京销售公司",
//   //   khflmc: "轻商务直营店",
//   //   id: 17361,
//   //   sskhid: 18338,
//   //   jmcity: "北京市",
//   //   mdmc: "北京市海淀区翠微印象城店",
//   //   lat: 39.912185,
//   //   jmarea: "海淀区",
//   // },
//   // {
//   //   mdid: 11176,
//   //   khmc: "北京市海淀区唐家岭奥莱店",
//   //   jmpro: "北京市",
//   //   sskhdm: "BJ0069",
//   //   lng: 116.273171,
//   //   wdfl: "lh6",
//   //   sskhfl: "xf",
//   //   khid: 22184,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xz",
//   //   mddm: "jshd06",
//   //   khdm: "jshd06",
//   //   wdmc: "领航三部",
//   //   sskhmc: "3X·北京睿尚公司(混合)",
//   //   khflmc: "主品牌直营店",
//   //   id: 17362,
//   //   sskhid: 15108,
//   //   jmcity: "北京市",
//   //   mdmc: "北京市海淀区唐家岭奥莱店",
//   //   lat: 40.066721,
//   //   jmarea: "海淀区",
//   // },
//   {
//     mdid: 8394,
//     khmc: "镇江市丁卯桥路吾悦广场店",
//     jmpro: "江苏省",
//     sskhdm: "JS0057",
//     lng: 119.496758,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 18509,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "szzj04",
//     khdm: "szzj04",
//     wdmc: "市场总代",
//     sskhmc: "江苏郎润公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17363,
//     sskhid: 13610,
//     jmcity: "镇江市",
//     mdmc: "镇江市丁卯桥路吾悦广场店",
//     lat: 32.176316,
//     jmarea: "京口区",
//   },
//   {
//     mdid: 8174,
//     khmc: "浙江宁波市恒一广场店",
//     jmpro: "浙江省",
//     sskhdm: "ZJ0121",
//     lng: 121.514497,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 18157,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "zlnb02",
//     khdm: "zlnb02",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·宁波销售公司",
//     khflmc: "轻商务直营店",
//     id: 17366,
//     sskhid: 21369,
//     jmcity: "宁波市",
//     mdmc: "浙江宁波市恒一广场店",
//     lat: 29.851122,
//     jmarea: "海曙区",
//   },
//   {
//     mdid: 10039,
//     khmc: "福建厦门市湖里万达室内步行街",
//     jmpro: "福建省",
//     sskhdm: "FJ0037",
//     lng: 118.177432,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 21112,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "mwxm02",
//     khdm: "mwxm02",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·福建销售公司",
//     khflmc: "轻商务直营店",
//     id: 17368,
//     sskhid: 19021,
//     jmcity: "厦门市",
//     mdmc: "福建厦门市湖里万达室内步行街",
//     lat: 24.504283,
//     jmarea: "湖里区",
//   },
//   {
//     mdid: 8748,
//     khmc: "福建晋江市陈埭吾悦广场店",
//     jmpro: "福建省",
//     sskhdm: "FJ0037",
//     lng: 118.600051,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 19195,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "mwjj01",
//     khdm: "mwjj01",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·福建销售公司",
//     khflmc: "轻商务直营店",
//     id: 17369,
//     sskhid: 19021,
//     jmcity: "泉州市",
//     mdmc: "福建晋江市陈埭吾悦广场店",
//     lat: 24.832433,
//     jmarea: "晋江市",
//   },
//   {
//     mdid: 11172,
//     khmc: "天水市秦州万达室内步行街店",
//     jmpro: "甘肃省",
//     sskhdm: "SX0086",
//     lng: 105.75388,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22179,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "sqts03",
//     khdm: "sqts03",
//     wdmc: "领航二部",
//     sskhmc: "2J·陕西秦越公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17370,
//     sskhid: 18329,
//     jmcity: "天水市",
//     mdmc: "天水市秦州万达室内步行街店",
//     lat: 34.58238,
//     jmarea: "秦州区",
//   },
//   {
//     mdid: 8306,
//     khmc: "开封市中山路轻商务店",
//     jmpro: "河南省",
//     sskhdm: "HN0093",
//     lng: 114.351336,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 18374,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xn",
//     mddm: "ywkf02",
//     khdm: "ywkf02",
//     wdmc: "轻商务管理中心",
//     sskhmc: "河南商丘辉盛公司（轻商务）",
//     khflmc: "轻商务加盟店",
//     id: 17371,
//     sskhid: 18589,
//     jmcity: "开封市",
//     mdmc: "开封市中山路轻商务店",
//     lat: 34.795977,
//     jmarea: "鼓楼区",
//   },
//   {
//     mdid: 6029,
//     khmc: "贵阳市观山湖区世纪城购物中心",
//     jmpro: "贵州省",
//     sskhdm: "GZ0049",
//     lng: 106.625136,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 14936,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "qlgy22",
//     khdm: "qlgy22",
//     wdmc: "领航一部",
//     sskhmc: "1J·贵州明志乐德公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17373,
//     sskhid: 11343,
//     jmcity: "贵阳市",
//     mdmc: "贵阳市观山湖区世纪城购物中心",
//     lat: 26.599147,
//     jmarea: "观山湖区",
//   },
//   {
//     mdid: 11174,
//     khmc: "舒城县万达室内步行街店",
//     jmpro: "安徽省",
//     sskhdm: "AH0011",
//     lng: 116.960213,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22181,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "wxsc02",
//     khdm: "wxsc02",
//     wdmc: "领航二部",
//     sskhmc: "2J·安徽郎胜公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 17375,
//     sskhid: 83,
//     jmcity: "六安市",
//     mdmc: "舒城县万达室内步行街店",
//     lat: 31.466529,
//     jmarea: "舒城县",
//   },
//   {
//     mdid: 7935,
//     khmc: "2X阿拉善左旗绿色之光店",
//     jmpro: "内蒙古自治区",
//     sskhdm: "NM0009",
//     lng: 105.697618,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 17804,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "myaz01",
//     khdm: "myaz01",
//     wdmc: "领航一部",
//     sskhmc: "1J·内蒙古优尚公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17376,
//     sskhid: 17208,
//     jmcity: "阿拉善盟",
//     mdmc: "阿拉善左旗绿色之光店",
//     lat: 38.838416,
//     jmarea: "阿拉善左旗",
//   },
//   {
//     mdid: 11207,
//     khmc: "陕西西安市新城区万和城店",
//     jmpro: "陕西省",
//     sskhdm: "SX0098",
//     lng: 108.994645,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22247,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "skxa56",
//     khdm: "skxa56",
//     wdmc: "轻商务管理中心",
//     sskhmc: "J·西安销售公司",
//     khflmc: "轻商务直营店",
//     id: 17377,
//     sskhid: 19258,
//     jmcity: "西安市",
//     mdmc: "陕西西安市新城区万和城店",
//     lat: 34.278771,
//     jmarea: "新城区",
//   },
//   {
//     mdid: 11205,
//     khmc: "白银市白银区工农路店",
//     jmpro: "甘肃省",
//     sskhdm: "SX0044",
//     lng: 104.167846,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22231,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "saby03",
//     khdm: "saby03",
//     wdmc: "领航二部",
//     sskhmc: "2J·陕西品行公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17372,
//     sskhid: 947,
//     jmcity: "白银市",
//     mdmc: "白银市白银区工农路店",
//     lat: 36.545544,
//     jmarea: "白银区",
//   },
//   {
//     mdid: 8229,
//     khmc: "凯里市国贸商场",
//     jmpro: "贵州省",
//     sskhdm: "GZ0133",
//     lng: 107.973268,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 18253,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "qlkl02",
//     khdm: "qlkl02",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州安凯销售公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17379,
//     sskhid: 21973,
//     jmcity: "黔东南苗族侗族自治州",
//     mdmc: "凯里市国贸商场",
//     lat: 26.580429,
//     jmarea: "凯里市",
//   },
//   {
//     mdid: 11191,
//     khmc: "贵州贵阳市龙湾万达室内步行街店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0108",
//     lng: 106.701472,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22212,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "qlgz11",
//     khdm: "qlgz11",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·贵州销售公司",
//     khflmc: "轻商务直营店",
//     id: 17339,
//     sskhid: 20980,
//     jmcity: "贵阳市",
//     mdmc: "贵州贵阳市龙湾万达室内步行街店",
//     lat: 26.522711,
//     jmarea: "花溪区",
//   },
//   {
//     mdid: 11173,
//     khmc: "绩溪县文峰路店",
//     jmpro: "安徽省",
//     sskhdm: "AH0011",
//     lng: 118.592917,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22180,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "wxjx03",
//     khdm: "wxjx03",
//     wdmc: "领航二部",
//     sskhmc: "2J·安徽郎胜公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 17381,
//     sskhid: 83,
//     jmcity: "宣城市",
//     mdmc: "绩溪县文峰路店",
//     lat: 30.063955,
//     jmarea: "绩溪县",
//   },
//   // {
//   //   mdid: 11227,
//   //   khmc: "通榆县开通大路店",
//   //   jmpro: "吉林省",
//   //   sskhdm: "JL0003",
//   //   lng: 123.086223,
//   //   wdfl: "lh2",
//   //   sskhfl: "xf",
//   //   khid: 22279,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xj",
//   //   mddm: "jety02",
//   //   khdm: "jety02",
//   //   wdmc: "领航二部",
//   //   sskhmc: "2X·吉林盛凯特公司(混合)",
//   //   khflmc: "主品牌加盟店",
//   //   id: 17380,
//   //   sskhid: 949,
//   //   jmcity: "白城市",
//   //   mdmc: "通榆县开通大路店",
//   //   lat: 44.806081,
//   //   jmarea: "通榆县",
//   // },
//   {
//     mdid: 11183,
//     khmc: "河南郑州市航海路丹尼斯店",
//     jmpro: "河南省",
//     sskhdm: "HN0006",
//     lng: 113.737593,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22202,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "zqzz02",
//     khdm: "zqzz02",
//     wdmc: "轻商务管理中心",
//     sskhmc: "J·郑州销售公司",
//     khflmc: "轻商务直营店",
//     id: 17383,
//     sskhid: 19019,
//     jmcity: "郑州市",
//     mdmc: "河南郑州市航海路丹尼斯店",
//     lat: 34.721796,
//     jmarea: "管城回族区",
//   },
//   {
//     mdid: 11167,
//     khmc: "兴义市富兴东路专卖店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0141",
//     lng: 104.918591,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22171,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "qjxy05",
//     khdm: "qjxy05",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州欣佰瑞公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17385,
//     sskhid: 22017,
//     jmcity: "黔西南布依族苗族自治州",
//     mdmc: "兴义市富兴东路专卖店",
//     lat: 25.088159,
//     jmarea: "兴义市",
//   },
//   {
//     mdid: 6941,
//     khmc: "赤峰三道街专卖店",
//     jmpro: "内蒙古自治区",
//     sskhdm: "LN0005",
//     lng: 118.955632,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 16295,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "lrcf03",
//     khdm: "lrcf03",
//     wdmc: "市场总代",
//     sskhmc: "辽宁晟昱成公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 15483,
//     sskhid: 205,
//     jmcity: "赤峰市",
//     mdmc: "赤峰三道街专卖店",
//     lat: 42.276924,
//     jmarea: "红山区",
//   },
//   {
//     mdid: 9640,
//     khmc: "宜阳县文化路店",
//     jmpro: "河南省",
//     sskhdm: "HN0139",
//     lng: 112.177202,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 20549,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ypyy05",
//     khdm: "ypyy05",
//     wdmc: "领航一部",
//     sskhmc: "1X·河南迈锦锐销售公司（直营）",
//     khflmc: "主品牌直营店",
//     id: 15485,
//     sskhid: 21987,
//     jmcity: "洛阳市",
//     mdmc: "宜阳县文化路店",
//     lat: 34.516688,
//     jmarea: "宜阳县",
//   },
//   {
//     mdid: 9385,
//     khmc: "政和县福地步行街专卖店",
//     jmpro: "福建省",
//     sskhdm: "FJ0135",
//     lng: 118.85244,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 20105,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "mdzh02",
//     khdm: "mdzh02",
//     wdmc: "领航一部",
//     sskhmc: "1X·福建润达直营销售公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 15484,
//     sskhid: 21974,
//     jmcity: "南平市",
//     mdmc: "政和县福地步行街专卖店",
//     lat: 27.36578,
//     jmarea: "政和县",
//   },
//   {
//     mdid: 3155,
//     khmc: "柘城专卖店（新）",
//     jmpro: "河南省",
//     sskhdm: "HN0032",
//     lng: 115.30706,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 2998,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "ypzc01",
//     khdm: "ypzc01",
//     wdmc: "领航一部",
//     sskhmc: "1J·河南新上利公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 15492,
//     sskhid: 186,
//     jmcity: "商丘市",
//     mdmc: "柘城县步行街店",
//     lat: 34.07574,
//     jmarea: "柘城县",
//   },
//   {
//     mdid: 9666,
//     khmc: "佛山市顺德区大良镇大融城店",
//     jmpro: "广东省",
//     sskhdm: "GD0118",
//     lng: 113.274033,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 20585,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "yqdl02",
//     khdm: "yqdl02",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东粤湾区(直营)",
//     khflmc: "主品牌直营店",
//     id: 15487,
//     sskhid: 21351,
//     jmcity: "佛山市",
//     mdmc: "佛山市顺德区大良镇大融城店",
//     lat: 22.82621,
//     jmarea: "顺德区",
//   },
//   {
//     mdid: 9647,
//     khmc: "云浮市云城区新世纪广场店",
//     jmpro: "广东省",
//     sskhdm: "GD0078",
//     lng: 112.02279,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 20560,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ymyf02",
//     khdm: "ymyf02",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东佛山(直营)",
//     khflmc: "主品牌直营店",
//     id: 15493,
//     sskhid: 16690,
//     jmcity: "云浮市",
//     mdmc: "云浮市云城区新世纪广场店",
//     lat: 22.93043,
//     jmarea: "云城区",
//   },
//   {
//     mdid: 9712,
//     khmc: "桂平市桂南路专卖店",
//     jmpro: "广西壮族自治区",
//     sskhdm: "GX0031",
//     lng: 110.07675,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 20646,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "grgp01",
//     khdm: "grgp01",
//     wdmc: "领航一部",
//     sskhmc: "1X·广西儒祺公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 15494,
//     sskhid: 12563,
//     jmcity: "贵港市",
//     mdmc: "桂平市桂南路专卖店",
//     lat: 23.38607,
//     jmarea: "桂平市",
//   },
//   {
//     mdid: 9791,
//     khmc: "广州市天河区美林广场店",
//     jmpro: "广东省",
//     sskhdm: "GD0029",
//     lng: 113.41556,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 20734,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ydgz31",
//     khdm: "ydgz31",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东广州(直营)",
//     khflmc: "主品牌直营店",
//     id: 15482,
//     sskhid: 2555,
//     jmcity: "广州市",
//     mdmc: "广州市天河区美林广场店",
//     lat: 23.10487,
//     jmarea: "天河区",
//   },
//   {
//     mdid: 2389,
//     khmc: "长沙市蔡锷北路专卖店",
//     jmpro: "湖南省",
//     sskhdm: "HN0092",
//     lng: 112.98189,
//     wdfl: "xg",
//     sskhfl: "xg",
//     khid: 2389,
//     sskhflmc: "零售客户",
//     xh: 1,
//     khfl: "xg",
//     mddm: "xcxs02",
//     khdm: "xcxs02",
//     wdmc: "零售客户",
//     sskhmc: "湖南长沙星沙公司(直营)",
//     khflmc: "零售客户",
//     id: 15496,
//     sskhid: 18349,
//     jmcity: "长沙市",
//     mdmc: "长沙市蔡锷北路专卖店",
//     lat: 28.20223,
//     jmarea: "开福区",
//   },
//   {
//     mdid: 9500,
//     khmc: "安溪县万达室内步行街店",
//     jmpro: "福建省",
//     sskhdm: "FJ0017",
//     lng: 118.222142,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 20311,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "mdax04",
//     khdm: "mdax04",
//     wdmc: "领航一部",
//     sskhmc: "1J·福建润达加盟销售公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 14168,
//     sskhid: 244,
//     jmcity: "泉州市",
//     mdmc: "安溪县万达室内步行街店",
//     lat: 25.070972,
//     jmarea: "安溪县",
//   },
//   {
//     mdid: 9635,
//     khmc: "扬州市五彩世界生活广场店",
//     jmpro: "江苏省",
//     sskhdm: "JS0057",
//     lng: 119.38302,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 20543,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "szyz14",
//     khdm: "szyz14",
//     wdmc: "市场总代",
//     sskhmc: "江苏郎润公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 15497,
//     sskhid: 13610,
//     jmcity: "扬州市",
//     mdmc: "扬州市五彩世界生活广场店",
//     lat: 32.385262,
//     jmarea: "邗江区",
//   },
//   {
//     mdid: 9637,
//     khmc: "富蕴县迎宾东路店",
//     jmpro: "新疆维吾尔自治区",
//     sskhdm: "XJ0046",
//     lng: 89.52819,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 20545,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "xyfy01",
//     khdm: "xyfy01",
//     wdmc: "市场总代",
//     sskhmc: "新疆仙羽公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 15498,
//     sskhid: 214,
//     jmcity: "阿勒泰地区",
//     mdmc: "富蕴县迎宾东路店",
//     lat: 46.99111,
//     jmarea: "富蕴县",
//   },
//   {
//     mdid: 9621,
//     khmc: "南和县建设大街店",
//     jmpro: "河北省",
//     sskhdm: "HB0007",
//     lng: 114.69756,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 20515,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "jynh01",
//     khdm: "jynh01",
//     wdmc: "市场总代",
//     sskhmc: "河北亿派客公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 15499,
//     sskhid: 1728,
//     jmcity: "邢台市",
//     mdmc: "南和县建设大街店",
//     lat: 37.00776,
//     jmarea: "南和县",
//   },
//   {
//     mdid: 11193,
//     khmc: "马鞍山市金鹰国际广场店",
//     jmpro: "安徽省",
//     sskhdm: "AH0110",
//     lng: 118.509243,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22214,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "wxma11",
//     khdm: "wxma11",
//     wdmc: "领航二部",
//     sskhmc: "2X·安徽晋盛东区(直营）",
//     khflmc: "主品牌直营店",
//     id: 17521,
//     sskhid: 21344,
//     jmcity: "马鞍山市",
//     mdmc: "马鞍山市金鹰国际广场店",
//     lat: 31.684948,
//     jmarea: "雨山区",
//   },
//   {
//     mdid: 11248,
//     khmc: "德化县瓷都大道万达室内步行街店",
//     jmpro: "福建省",
//     sskhdm: "FJ0017",
//     lng: 118.223492,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22306,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "mddh03",
//     khdm: "mddh03",
//     wdmc: "领航一部",
//     sskhmc: "1J·福建润达加盟销售公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17522,
//     sskhid: 244,
//     jmcity: "泉州市",
//     mdmc: "德化县瓷都大道万达室内步行街店",
//     lat: 25.483691,
//     jmarea: "德化县",
//   },
//   {
//     mdid: 7078,
//     khmc: "宜昌夷兴大道专卖店(小溪塔）",
//     jmpro: "湖北省",
//     sskhdm: "HB0038",
//     lng: 111.324868,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 14206,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "eryc04c",
//     khdm: "eryc04",
//     wdmc: "市场总代",
//     sskhmc: "湖北仁祥公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17523,
//     sskhid: 185,
//     jmcity: "宜昌市",
//     mdmc: "宜昌市小溪塔夷兴大道店",
//     lat: 30.76959,
//     jmarea: "夷陵区",
//   },
//   {
//     mdid: 547,
//     khmc: "洪湖专卖店",
//     jmpro: "湖北省",
//     sskhdm: "HB0038",
//     lng: 113.464673,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 547,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "erhh01",
//     khdm: "erhh01",
//     wdmc: "市场总代",
//     sskhmc: "湖北仁祥公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17524,
//     sskhid: 185,
//     jmcity: "荆州市",
//     mdmc: "洪湖市宏伟路专卖店",
//     lat: 29.810813,
//     jmarea: "洪湖市",
//   },
//   {
//     mdid: 11179,
//     khmc: "湄潭县茶乡路店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0048",
//     lng: 107.486147,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22195,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "qxmt03",
//     khdm: "qxmt03",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州晓星公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17530,
//     sskhid: 1749,
//     jmcity: "遵义市",
//     mdmc: "湄潭县茶乡路店",
//     lat: 27.766599,
//     jmarea: "湄潭县",
//   },
//   {
//     mdid: 7694,
//     khmc: "来凤县步行街专卖店",
//     jmpro: "湖北省",
//     sskhdm: "HB0038",
//     lng: 109.40774,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 17389,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "erlf03",
//     khdm: "erlf03",
//     wdmc: "市场总代",
//     sskhmc: "湖北仁祥公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17527,
//     sskhid: 185,
//     jmcity: "恩施土家族苗族自治州",
//     mdmc: "来凤县步行街专卖店",
//     lat: 29.505951,
//     jmarea: "来凤县",
//   },
//   {
//     mdid: 11218,
//     khmc: "中山市利和广场店",
//     jmpro: "广东省",
//     sskhdm: "GD0118",
//     lng: 113.384056,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 22263,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "yqzs04",
//     khdm: "yqzs04",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东粤湾区(直营)",
//     khflmc: "主品牌直营店",
//     id: 17531,
//     sskhid: 21351,
//     jmcity: "中山市",
//     mdmc: "中山市利和广场店",
//     lat: 22.512289,
//     jmarea: "东区街道",
//   },
//   {
//     mdid: 3440,
//     khmc: "邢台市中兴西大街专卖店",
//     jmpro: "河北省",
//     sskhdm: "HB0062",
//     lng: 114.47594,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 14520,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "jrxt01",
//     khdm: "jrxt01",
//     wdmc: "市场总代",
//     sskhmc: "河北建邦公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17532,
//     sskhid: 14429,
//     jmcity: "邢台市",
//     mdmc: "邢台市中兴西大街专卖店",
//     lat: 37.060721,
//     jmarea: "桥西区",
//   },
//   {
//     mdid: 9194,
//     khmc: "安徽合肥市滨湖区悦方IDMALL店",
//     jmpro: "安徽省",
//     sskhdm: "AH0020",
//     lng: 117.304716,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 19843,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "anhf24",
//     khdm: "anhf24",
//     wdmc: "轻商务管理中心",
//     sskhmc: "J·合肥销售公司",
//     khflmc: "轻商务直营店",
//     id: 17533,
//     sskhid: 19022,
//     jmcity: "合肥市",
//     mdmc: "安徽合肥市滨湖区悦方IDMALL店",
//     lat: 31.739883,
//     jmarea: "包河区",
//   },
//   {
//     mdid: 9965,
//     khmc: "大同市华亿摩尔城店",
//     jmpro: "山西省",
//     sskhdm: "SX0128",
//     lng: 113.185028,
//     wdfl: "lh4",
//     sskhfl: "xd",
//     khid: 21014,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "jfdt05",
//     khdm: "jfdt05",
//     wdmc: "市场直营",
//     sskhmc: "5X·山西菲芮平城公司（直营）",
//     khflmc: "主品牌直营店",
//     id: 17536,
//     sskhid: 21599,
//     jmcity: "大同市",
//     mdmc: "大同市华亿摩尔城店",
//     lat: 40.042018,
//     jmarea: "云冈区",
//   },
//   {
//     mdid: 485,
//     khmc: "巧家县新华南路专卖店",
//     jmpro: "云南省",
//     sskhdm: "YN0064",
//     lng: 102.93786,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 485,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "dhqj03",
//     khdm: "dhqj03",
//     wdmc: "市场总代",
//     sskhmc: "云南互轩公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17537,
//     sskhid: 14607,
//     jmcity: "昭通市",
//     mdmc: "巧家县新华南路专卖店",
//     lat: 26.901008,
//     jmarea: "巧家县",
//   },
//   {
//     mdid: 11252,
//     khmc: "河南郑州市郑汴路印象汇店",
//     jmpro: "河南省",
//     sskhdm: "HN0006",
//     lng: 113.725512,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22311,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "zqzz03",
//     khdm: "zqzz03",
//     wdmc: "轻商务管理中心",
//     sskhmc: "J·郑州销售公司",
//     khflmc: "轻商务直营店",
//     id: 17538,
//     sskhid: 19019,
//     jmcity: "郑州市",
//     mdmc: "河南郑州市郑汴路印象汇店",
//     lat: 34.748379,
//     jmarea: "金水区",
//   },
//   {
//     mdid: 8176,
//     khmc: "佛山市三水区万达室内步行街",
//     jmpro: "广东省",
//     sskhdm: "GD0078",
//     lng: 112.905378,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 18160,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ymss02",
//     khdm: "ymss02",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东佛山(直营)",
//     khflmc: "主品牌直营店",
//     id: 17539,
//     sskhid: 16690,
//     jmcity: "佛山市",
//     mdmc: "佛山市三水区万达室内步行街",
//     lat: 23.177085,
//     jmarea: "三水区",
//   },
//   {
//     mdid: 11232,
//     khmc: "东莞市大岭山镇教育中路店",
//     jmpro: "广东省",
//     sskhdm: "GD0117",
//     lng: 113.841416,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 22285,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "yjdl02",
//     khdm: "yjdl02",
//     wdmc: "广东大区",
//     sskhmc: "1J·广东加盟",
//     khflmc: "主品牌加盟店",
//     id: 17541,
//     sskhid: 21350,
//     jmcity: "东莞市",
//     mdmc: "东莞市大岭山镇教育中路店",
//     lat: 22.903593,
//     jmarea: "大岭山镇",
//   },
//   {
//     mdid: 11231,
//     khmc: "贞丰县富民路金融公园店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0140",
//     lng: 105.648496,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22283,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "qxzf03",
//     khdm: "qxzf03",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州喜美高公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 17540,
//     sskhid: 22016,
//     jmcity: "黔西南布依族苗族自治州",
//     mdmc: "贞丰县富民路金融公园店",
//     lat: 25.386381,
//     jmarea: "贞丰县",
//   },
//   {
//     mdid: 5028,
//     khmc: "乐至县商业广场专卖店",
//     jmpro: "四川省",
//     sskhdm: "SC0061",
//     lng: 105.026731,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 13761,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sxlz01",
//     khdm: "sxlz01",
//     wdmc: "市场总代",
//     sskhmc: "四川启界公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17542,
//     sskhid: 14317,
//     jmcity: "资阳市",
//     mdmc: "乐至县商业广场专卖店",
//     lat: 30.278813,
//     jmarea: "乐至县",
//   },
//   {
//     mdid: 3850,
//     khmc: "岳阳市巴陵路武商商场",
//     jmpro: "湖南省",
//     sskhdm: "HN0113",
//     lng: 113.106903,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 12225,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "xzyy04",
//     khdm: "xzyy04",
//     wdmc: "领航二部",
//     sskhmc: "2X·湖南郎博益阳（直营）",
//     khflmc: "主品牌直营店",
//     id: 17544,
//     sskhid: 21347,
//     jmcity: "岳阳市",
//     mdmc: "岳阳市巴陵路武商商场",
//     lat: 29.374256,
//     jmarea: "岳阳楼区",
//   },
//   {
//     mdid: 5238,
//     khmc: "益阳市赫山桃花仑中路店",
//     jmpro: "湖南省",
//     sskhdm: "HN0113",
//     lng: 112.370846,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 13949,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "xzyy06",
//     khdm: "xzyy06",
//     wdmc: "领航二部",
//     sskhmc: "2X·湖南郎博益阳（直营）",
//     khflmc: "主品牌直营店",
//     id: 17548,
//     sskhid: 21347,
//     jmcity: "益阳市",
//     mdmc: "益阳市赫山桃花仑中路店",
//     lat: 28.579232,
//     jmarea: "赫山区",
//   },
//   {
//     mdid: 7610,
//     khmc: "江油市汇星百货商场",
//     jmpro: "四川省",
//     sskhdm: "SC0073",
//     lng: 104.742681,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 17269,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "sxjy06",
//     khdm: "sxjy06",
//     wdmc: "市场总代",
//     sskhmc: "四川闽画公司（直营）",
//     khflmc: "主品牌直营店",
//     id: 17549,
//     sskhid: 16096,
//     jmcity: "绵阳市",
//     mdmc: "江油市汇星百货商场",
//     lat: 31.773738,
//     jmarea: "江油市",
//   },
//   {
//     mdid: 6690,
//     khmc: "吴江芦墟专卖店",
//     jmpro: "江苏省",
//     sskhdm: "JS0065",
//     lng: 120.839943,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 2900,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sylx01b",
//     khdm: "sylx01",
//     wdmc: "市场总代",
//     sskhmc: "江苏御旨公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17551,
//     sskhid: 14925,
//     jmcity: "苏州市",
//     mdmc: "吴江市芦墟镇浦南路459号店",
//     lat: 31.00715,
//     jmarea: "吴江区",
//   },
//   {
//     mdid: 7589,
//     khmc: "内江市万达室内步行街店",
//     jmpro: "四川省",
//     sskhdm: "SC0073",
//     lng: 105.041769,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 17252,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "sxnj02",
//     khdm: "sxnj02",
//     wdmc: "市场总代",
//     sskhmc: "四川闽画公司（直营）",
//     khflmc: "主品牌直营店",
//     id: 17552,
//     sskhid: 16096,
//     jmcity: "内江市",
//     mdmc: "内江市万达室内步行街店",
//     lat: 29.604385,
//     jmarea: "东兴区",
//   },
//   {
//     mdid: 11226,
//     khmc: "新乡市平原新区奥特莱斯店",
//     jmpro: "河南省",
//     sskhdm: "HN0127",
//     lng: 113.698046,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 22278,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ynxx09",
//     khdm: "ynxx09",
//     wdmc: "领航一部",
//     sskhmc: "1J·河南丰扬公司（直营）",
//     khflmc: "主品牌直营店",
//     id: 17556,
//     sskhid: 21587,
//     jmcity: "新乡市",
//     mdmc: "新乡市平原新区奥特莱斯店",
//     lat: 34.991147,
//     jmarea: "平原新区",
//   },
//   {
//     mdid: 5883,
//     khmc: "韶关风度中路店",
//     jmpro: "广东省",
//     sskhdm: "GD0029",
//     lng: 113.598563,
//     wdfl: "lh5",
//     sskhfl: "xf",
//     khid: 14787,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "ydsg02",
//     khdm: "ydsg02",
//     wdmc: "广东大区",
//     sskhmc: "1X·广东广州(直营)",
//     khflmc: "主品牌直营店",
//     id: 17564,
//     sskhid: 2555,
//     jmcity: "韶关市",
//     mdmc: "韶关风度中路店",
//     lat: 24.805196,
//     jmarea: "浈江区",
//   },
//   // {
//   //   mdid: 10648,
//   //   khmc: "景德镇市华达百货",
//   //   jmpro: "江西省",
//   //   sskhdm: "JX0067",
//   //   lng: 117.205399,
//   //   wdfl: "lh1",
//   //   sskhfl: "xf",
//   //   khid: 21625,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xz",
//   //   mddm: "gyjd08",
//   //   khdm: "gyjd08",
//   //   wdmc: "领航一部",
//   //   sskhmc: "1X·江西睿毅公司(混合)",
//   //   khflmc: "主品牌直营店",
//   //   id: 17566,
//   //   sskhid: 15110,
//   //   jmcity: "景德镇市",
//   //   mdmc: "景德镇市华达百货",
//   //   lat: 29.292912,
//   //   jmarea: "珠山区",
//   // },
//   {
//     mdid: 2834,
//     khmc: "金华市宾虹路专卖店",
//     jmpro: "浙江省",
//     sskhdm: "ZJ0028",
//     lng: 119.651703,
//     wdfl: "lh6",
//     sskhfl: "xf",
//     khid: 2834,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "zxjh02",
//     khdm: "zxjh02",
//     wdmc: "领航三部",
//     sskhmc: "3X·浙江盈尚公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17543,
//     sskhid: 87,
//     jmcity: "金华市",
//     mdmc: "金华市宾虹路专卖店",
//     lat: 29.084428,
//     jmarea: "婺城区",
//   },
//   {
//     mdid: 9608,
//     khmc: "南充市三公街专卖店",
//     jmpro: "四川省",
//     sskhdm: "SC0050",
//     lng: 106.088265,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 20500,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sxnc02",
//     khdm: "sxnc02",
//     wdmc: "市场总代",
//     sskhmc: "四川西蜀天地公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17568,
//     sskhid: 193,
//     jmcity: "南充市",
//     mdmc: "南充市三公街专卖店",
//     lat: 30.795557,
//     jmarea: "顺庆区",
//   },
//   {
//     mdid: 8720,
//     khmc: "六盘水万达室内步行街店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0140",
//     lng: 104.858816,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 19130,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "qjlp01",
//     khdm: "qjlp01",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州喜美高公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17569,
//     sskhid: 22016,
//     jmcity: "六盘水市",
//     mdmc: "六盘水万达室内步行街店",
//     lat: 26.576102,
//     jmarea: "钟山区",
//   },
//   // {
//   //   mdid: 9197,
//   //   khmc: "江西宜春市润达国际购物中心店",
//   //   jmpro: "江西省",
//   //   sskhdm: "JX0010",
//   //   lng: 114.371538,
//   //   wdfl: "xk",
//   //   sskhfl: "xk",
//   //   khid: 19851,
//   //   sskhflmc: "轻商务管理中心",
//   //   xh: 1,
//   //   khfl: "xm",
//   //   mddm: "gzyc09",
//   //   khdm: "gzyc09",
//   //   wdmc: "轻商务管理中心",
//   //   sskhmc: "X·南昌销售公司",
//   //   khflmc: "轻商务直营店",
//   //   id: 17570,
//   //   sskhid: 19020,
//   //   jmcity: "宜春市",
//   //   mdmc: "江西宜春市润达国际购物中心店",
//   //   lat: 27.794724,
//   //   jmarea: "袁州区",
//   // },
//   {
//     mdid: 5204,
//     khmc: "当涂专卖店（新）",
//     jmpro: "安徽省",
//     sskhdm: "AH0011",
//     lng: 118.490623,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 463,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "wxdt01c",
//     khdm: "wxdt01",
//     wdmc: "领航二部",
//     sskhmc: "2J·安徽郎胜公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 17563,
//     sskhid: 83,
//     jmcity: "马鞍山市",
//     mdmc: "当涂县东大街311-313号专卖店",
//     lat: 31.554407,
//     jmarea: "当涂县",
//   },
//   {
//     mdid: 9590,
//     khmc: "安徽合肥市庐阳区万科广场店",
//     jmpro: "安徽省",
//     sskhdm: "AH0020",
//     lng: 117.234206,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 20478,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "anhf31",
//     khdm: "anhf31",
//     wdmc: "轻商务管理中心",
//     sskhmc: "J·合肥销售公司",
//     khflmc: "轻商务直营店",
//     id: 17572,
//     sskhid: 19022,
//     jmcity: "合肥市",
//     mdmc: "安徽合肥市庐阳区万科广场店",
//     lat: 31.892279,
//     jmarea: "庐阳区",
//   },
//   {
//     mdid: 11246,
//     khmc: "凌源市遵化街潮汇尚品商场",
//     jmpro: "辽宁省",
//     sskhdm: "LN0005",
//     lng: 119.40527,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22299,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "lrly07",
//     khdm: "lrly07",
//     wdmc: "市场总代",
//     sskhmc: "辽宁晟昱成公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 17567,
//     sskhid: 205,
//     jmcity: "朝阳市",
//     mdmc: "凌源市遵化街潮汇尚品商场",
//     lat: 41.247101,
//     jmarea: "凌源市",
//   },
//   {
//     mdid: 11170,
//     khmc: "南江县光雾山大道店",
//     jmpro: "四川省",
//     sskhdm: "SC0050",
//     lng: 106.840689,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22174,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sxnj05",
//     khdm: "sxnj05",
//     wdmc: "市场总代",
//     sskhmc: "四川西蜀天地公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17574,
//     sskhid: 193,
//     jmcity: "巴中市",
//     mdmc: "南江县光雾山大道店",
//     lat: 32.352762,
//     jmarea: "南江县",
//   },
//   {
//     mdid: 724,
//     khmc: "南部县万达北街店",
//     jmpro: "四川省",
//     sskhdm: "SC0050",
//     lng: 106.063315,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 724,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sxnb01",
//     khdm: "sxnb01",
//     wdmc: "市场总代",
//     sskhmc: "四川西蜀天地公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17575,
//     sskhid: 193,
//     jmcity: "南充市",
//     mdmc: "南部县万达北街店",
//     lat: 31.352144,
//     jmarea: "南部县",
//   },
//   {
//     mdid: 6399,
//     khmc: "阆中市俊豪购物中心店",
//     jmpro: "四川省",
//     sskhdm: "SC0050",
//     lng: 105.972732,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 15370,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sxlz04",
//     khdm: "sxlz04",
//     wdmc: "市场总代",
//     sskhmc: "四川西蜀天地公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17571,
//     sskhid: 193,
//     jmcity: "南充市",
//     mdmc: "阆中市俊豪购物中心店",
//     lat: 31.578819,
//     jmarea: "阆中市",
//   },
//   {
//     mdid: 11228,
//     khmc: "石家庄市裕泰路智汇城店",
//     jmpro: "河北省",
//     sskhdm: "HB0062",
//     lng: 114.539176,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22280,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "jrsj29",
//     khdm: "jrsj29",
//     wdmc: "市场总代",
//     sskhmc: "河北建邦公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17576,
//     sskhid: 14429,
//     jmcity: "石家庄市",
//     mdmc: "石家庄市裕泰路智汇城店",
//     lat: 37.9953,
//     jmarea: "裕华区",
//   },
//   {
//     mdid: 1007,
//     khmc: "满城县玉川路专卖店",
//     jmpro: "河北省",
//     sskhdm: "HB0007",
//     lng: 116.42699,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 1007,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "jrmc01",
//     khdm: "jrmc01",
//     wdmc: "市场总代",
//     sskhmc: "河北亿派客公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17577,
//     sskhid: 1728,
//     jmcity: "保定市",
//     mdmc: "满城县玉川路专卖店",
//     lat: 39.846256,
//     jmarea: "满城区",
//   },
//   {
//     mdid: 4717,
//     khmc: "曲周县新华路专卖店",
//     jmpro: "河北省",
//     sskhdm: "HB0007",
//     lng: 115.01431,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 13388,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "jrqz01",
//     khdm: "jrqz01",
//     wdmc: "市场总代",
//     sskhmc: "河北亿派客公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17578,
//     sskhid: 1728,
//     jmcity: "邯郸市",
//     mdmc: "曲周县新华路专卖店 ",
//     lat: 36.909109,
//     jmarea: "曲周县",
//   },
//   {
//     mdid: 7151,
//     khmc: "洛阳泉舜购物广场专厅",
//     jmpro: "河南省",
//     sskhdm: "hn0036",
//     lng: 112.454499,
//     wdfl: "xg",
//     sskhfl: "xg",
//     khid: 19390,
//     sskhflmc: "零售客户",
//     xh: 1,
//     khfl: "xg",
//     mddm: "yyly09",
//     khdm: "yyly09",
//     wdmc: "零售客户",
//     sskhmc: "河南洛阳凯利金公司(直营)",
//     khflmc: "零售客户",
//     id: 17581,
//     sskhid: 337,
//     jmcity: "洛阳市",
//     mdmc: "洛阳泉舜购物广场专厅",
//     lat: 34.612866,
//     jmarea: "洛龙区",
//   },
//   {
//     mdid: 4707,
//     khmc: "淮南龙湖路一号专卖店",
//     jmpro: "安徽省",
//     sskhdm: "ah0013",
//     lng: 117.01736,
//     wdfl: "xg",
//     sskhfl: "xg",
//     khid: 18877,
//     sskhflmc: "零售客户",
//     xh: 1,
//     khfl: "xg",
//     mddm: "wlhn04",
//     khdm: "wlhn04",
//     wdmc: "零售客户",
//     sskhmc: "安徽淮南广昇公司(直营)",
//     khflmc: "零售客户",
//     id: 17582,
//     sskhid: 412,
//     jmcity: "淮南市",
//     mdmc: "淮南龙湖路一号专卖店",
//     lat: 32.643047,
//     jmarea: "田家庵区",
//   },
//   {
//     mdid: 9875,
//     khmc: "陕西西安市高新万达室内步行街店",
//     jmpro: "陕西省",
//     sskhdm: "SX0098",
//     lng: 108.891823,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 20900,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "skxa45",
//     khdm: "skxa45",
//     wdmc: "轻商务管理中心",
//     sskhmc: "J·西安销售公司",
//     khflmc: "轻商务直营店",
//     id: 17585,
//     sskhid: 19258,
//     jmcity: "西安市",
//     mdmc: "陕西西安市高新万达室内步行街店",
//     lat: 34.208187,
//     jmarea: "雁塔区",
//   },
//   // {
//   //   mdid: 6996,
//   //   khmc: "北京市昌平区回龙观华联购物中心店",
//   //   jmpro: "北京市",
//   //   sskhdm: "BJ0069",
//   //   lng: 116.319095,
//   //   wdfl: "lh6",
//   //   sskhfl: "xf",
//   //   khid: 16414,
//   //   sskhflmc: "领航管理中心",
//   //   xh: 1,
//   //   khfl: "xz",
//   //   mddm: "jshl02",
//   //   khdm: "jshl02",
//   //   wdmc: "领航三部",
//   //   sskhmc: "3X·北京睿尚公司(混合)",
//   //   khflmc: "主品牌直营店",
//   //   id: 17586,
//   //   sskhid: 15108,
//   //   jmcity: "北京市",
//   //   mdmc: "北京市昌平区回龙观华联购物中心店",
//   //   lat: 40.07636,
//   //   jmarea: "昌平区",
//   // },
//   {
//     mdid: 5794,
//     khmc: "安阳市唐子巷2店",
//     jmpro: "河南省",
//     sskhdm: "hn0034",
//     lng: 114.351245,
//     wdfl: "xg",
//     sskhfl: "xg",
//     khid: 19383,
//     sskhflmc: "零售客户",
//     xh: 1,
//     khfl: "xg",
//     mddm: "yaay07",
//     khdm: "yaay07",
//     wdmc: "零售客户",
//     sskhmc: "河南安阳郎晟公司(直营)",
//     khflmc: "零售客户",
//     id: 17583,
//     sskhid: 230,
//     jmcity: "安阳市",
//     mdmc: "安阳市唐子巷2店",
//     lat: 36.100599,
//     jmarea: "文峰区",
//   },
//   {
//     mdid: 7942,
//     khmc: "2X杭锦后旗中山南路店",
//     jmpro: "内蒙古自治区",
//     sskhdm: "NM0009",
//     lng: 107.146563,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 17811,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "myhs01",
//     khdm: "myhs01",
//     wdmc: "领航一部",
//     sskhmc: "1J·内蒙古优尚公司(混合)",
//     khflmc: "主品牌直营店",
//     id: 17588,
//     sskhid: 17208,
//     jmcity: "巴彦淖尔市",
//     mdmc: "杭锦后旗中山南路店",
//     lat: 40.887356,
//     jmarea: "杭锦后旗",
//   },
//   {
//     mdid: 4356,
//     khmc: "安阳市林州专卖店",
//     jmpro: "河南省",
//     sskhdm: "hn0034",
//     lng: 113.82561,
//     wdfl: "xg",
//     sskhfl: "xg",
//     khid: 19382,
//     sskhflmc: "零售客户",
//     xh: 1,
//     khfl: "xg",
//     mddm: "yaay03",
//     khdm: "yaay03",
//     wdmc: "零售客户",
//     sskhmc: "河南安阳郎晟公司(直营)",
//     khflmc: "零售客户",
//     id: 17584,
//     sskhid: 230,
//     jmcity: "安阳市",
//     mdmc: "安阳市林州专卖店",
//     lat: 36.062201,
//     jmarea: "林州市",
//   },
//   {
//     mdid: 8151,
//     khmc: "夏津县中山路家庭号专厅",
//     jmpro: "山东省",
//     sskhdm: "SD0026",
//     lng: 116.006039,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 18120,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "lkxj02",
//     khdm: "lkxj02",
//     wdmc: "市场总代",
//     sskhmc: "山东凯翼顺公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17442,
//     sskhid: 86,
//     jmcity: "德州市",
//     mdmc: "夏津县中山路家庭号专厅",
//     lat: 36.954835,
//     jmarea: "夏津县",
//   },
//   {
//     mdid: 7246,
//     khmc: "贵阳市都司青禾店",
//     jmpro: "贵州省",
//     sskhdm: "GZ0142",
//     lng: 106.707389,
//     wdfl: "lh1",
//     sskhfl: "xf",
//     khid: 16767,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "qlgy28",
//     khdm: "qlgy28",
//     wdmc: "领航一部",
//     sskhmc: "1X·贵州贵阳销售公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17565,
//     sskhid: 22018,
//     jmcity: "贵阳市",
//     mdmc: "贵阳市都司青禾店",
//     lat: 26.574012,
//     jmarea: "南明区",
//   },
//   {
//     mdid: 11237,
//     khmc: "永川区红河中路店",
//     jmpro: "重庆市",
//     sskhdm: "CQ0070",
//     lng: 105.941854,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22290,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "yfyc10",
//     khdm: "yfyc10",
//     wdmc: "市场总代",
//     sskhmc: "重庆成积汇利公司（直营）",
//     khflmc: "主品牌直营店",
//     id: 17590,
//     sskhid: 15116,
//     jmcity: "重庆市",
//     mdmc: "永川区红河中路店",
//     lat: 29.356103,
//     jmarea: "永川区",
//   },
//   {
//     mdid: 11244,
//     khmc: "随州市解放路店",
//     jmpro: "湖北省",
//     sskhdm: "HB0039",
//     lng: 113.372147,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22296,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "egsz02",
//     khdm: "egsz02",
//     wdmc: "市场总代",
//     sskhmc: "湖北国仁公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17591,
//     sskhid: 13344,
//     jmcity: "随州市",
//     mdmc: "随州市解放路店",
//     lat: 31.712945,
//     jmarea: "曾都区",
//   },
//   {
//     mdid: 7604,
//     khmc: "睢宁县睢城镇中山路",
//     jmpro: "江苏省",
//     sskhdm: "JS0025",
//     lng: 117.94864,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 15286,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "sysn02b",
//     khdm: "sysn02",
//     wdmc: "市场总代",
//     sskhmc: "江苏御玺公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17593,
//     sskhid: 215,
//     jmcity: "徐州市",
//     mdmc: "睢宁县府前路专卖店",
//     lat: 33.89856,
//     jmarea: "睢宁县",
//   },
//   {
//     mdid: 11272,
//     khmc: "株洲市天台路步步高广场",
//     jmpro: "湖南省",
//     sskhdm: "HN0107",
//     lng: 113.130319,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 22338,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "xxzz01",
//     khdm: "xxzz01",
//     wdmc: "领航二部",
//     sskhmc: "2J·湖南佳昂公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17594,
//     sskhid: 20555,
//     jmcity: "株洲市",
//     mdmc: "株洲市天台路步步高广场",
//     lat: 27.825888,
//     jmarea: "天元区",
//   },
//   {
//     mdid: 8163,
//     khmc: "长沙市岳麓区枫林路专卖店",
//     jmpro: "湖南省",
//     sskhdm: "HN0040",
//     lng: 112.923446,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 18138,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "xxcs04",
//     khdm: "xxcs04",
//     wdmc: "领航二部",
//     sskhmc: "2J·湖南晓星公司(加盟)",
//     khflmc: "主品牌加盟店",
//     id: 17595,
//     sskhid: 211,
//     jmcity: "长沙市",
//     mdmc: "长沙市岳麓区枫林路专卖店",
//     lat: 28.20897,
//     jmarea: "岳麓区",
//   },
//   {
//     mdid: 4831,
//     khmc: "安康市金州路时代广场",
//     jmpro: "陕西省",
//     sskhdm: "SX0086",
//     lng: 109.02701,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 13533,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "sqak02",
//     khdm: "sqak02",
//     wdmc: "领航二部",
//     sskhmc: "2J·陕西秦越公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17596,
//     sskhid: 18329,
//     jmcity: "安康市",
//     mdmc: "安康市金州路时代广场",
//     lat: 32.692557,
//     jmarea: "汉滨区",
//   },
//   {
//     mdid: 9096,
//     khmc: "天津市滨海新区永旺梦乐城店",
//     jmpro: "天津市",
//     sskhdm: "TJ0109",
//     lng: 117.729911,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 19685,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "jttj09",
//     khdm: "jttj09",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·天津销售公司",
//     khflmc: "轻商务直营店",
//     id: 17601,
//     sskhid: 21120,
//     jmcity: "天津市",
//     mdmc: "天津市滨海新区永旺梦乐城店",
//     lat: 39.031278,
//     jmarea: "滨海新区",
//   },
//   {
//     mdid: 11259,
//     khmc: "江苏南京市新百商场",
//     jmpro: "江苏省",
//     sskhdm: "JS0058",
//     lng: 118.785037,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22323,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "ssnj10",
//     khdm: "ssnj10",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·南京销售公司",
//     khflmc: "轻商务直营店",
//     id: 17602,
//     sskhid: 19256,
//     jmcity: "南京市",
//     mdmc: "江苏南京市新百商场",
//     lat: 32.040751,
//     jmarea: "秦淮区",
//   },
//   {
//     mdid: 7820,
//     khmc: "歙县专卖店",
//     jmpro: "安徽省",
//     sskhdm: "AH0011",
//     lng: 118.433084,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 461,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xj",
//     mddm: "wxsx01b",
//     khdm: "wxsx01",
//     wdmc: "领航二部",
//     sskhmc: "2J·安徽郎胜公司(混合)",
//     khflmc: "主品牌加盟店",
//     id: 17604,
//     sskhid: 83,
//     jmcity: "黄山市",
//     mdmc: "歙县徽州路专卖店",
//     lat: 29.867675,
//     jmarea: "歙县",
//   },
//   {
//     mdid: 11239,
//     khmc: "新沂市上海路吾悦广场店",
//     jmpro: "江苏省",
//     sskhdm: "JS0057",
//     lng: 118.328617,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22292,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "szxy02",
//     khdm: "szxy02",
//     wdmc: "市场总代",
//     sskhmc: "江苏郎润公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17605,
//     sskhid: 13610,
//     jmcity: "徐州市",
//     mdmc: "新沂市上海路吾悦广场店",
//     lat: 34.359464,
//     jmarea: "新沂市",
//   },
//   {
//     mdid: 11238,
//     khmc: "宿迁市青海湖路吾悦广场店",
//     jmpro: "江苏省",
//     sskhdm: "JS0057",
//     lng: 118.24622,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 22291,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "szsq06",
//     khdm: "szsq06",
//     wdmc: "市场总代",
//     sskhmc: "江苏郎润公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17606,
//     sskhid: 13610,
//     jmcity: "宿迁市",
//     mdmc: "宿迁市青海湖路吾悦广场店",
//     lat: 33.949813,
//     jmarea: "宿城区",
//   },
//   {
//     mdid: 8001,
//     khmc: "郴州市友阿国际广场",
//     jmpro: "湖南省",
//     sskhdm: "HN0041",
//     lng: 113.027092,
//     wdfl: "lh2",
//     sskhfl: "xf",
//     khid: 17897,
//     sskhflmc: "领航管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "xzcz06",
//     khdm: "xzcz06",
//     wdmc: "领航二部",
//     sskhmc: "2X·湖南郎博公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17609,
//     sskhid: 11341,
//     jmcity: "郴州市",
//     mdmc: "郴州市友阿国际广场",
//     lat: 25.80433,
//     jmarea: "北湖区",
//   },
//   {
//     mdid: 6199,
//     khmc: "邢台市新华路天一城店",
//     jmpro: "河北省",
//     sskhdm: "HB0062",
//     lng: 114.497816,
//     wdfl: "sc2",
//     sskhfl: "xd",
//     khid: 15126,
//     sskhflmc: "市场管理中心",
//     xh: 1,
//     khfl: "xz",
//     mddm: "jrxt05",
//     khdm: "jrxt05",
//     wdmc: "市场总代",
//     sskhmc: "河北建邦公司(直营)",
//     khflmc: "主品牌直营店",
//     id: 17612,
//     sskhid: 14429,
//     jmcity: "邢台市",
//     mdmc: "邢台市新华路天一城店",
//     lat: 37.07644,
//     jmarea: "桥东区",
//   },
//   {
//     mdid: 11254,
//     khmc: "山东烟台市莱山区万象汇店",
//     jmpro: "山东省",
//     sskhdm: "SD0084",
//     lng: 121.450269,
//     wdfl: "xk",
//     sskhfl: "xk",
//     khid: 22313,
//     sskhflmc: "轻商务管理中心",
//     xh: 1,
//     khfl: "xm",
//     mddm: "ljyt05",
//     khdm: "ljyt05",
//     wdmc: "轻商务管理中心",
//     sskhmc: "X·青岛销售公司",
//     khflmc: "轻商务直营店",
//     id: 17613,
//     sskhid: 19257,
//     jmcity: "烟台市",
//     mdmc: "山东烟台市莱山区万象汇店",
//     lat: 37.471367,
//     jmarea: "莱山区",
//   },
// ];
const mapInt = () => {
  let copyData;
  var polygon;
  // 百度地图API功能
  var map = new BMap.Map("allmap");
  var point = new BMap.Point(116.404, 39.915);
  map.centerAndZoom(point, 5);
  map.enableScrollWheelZoom(true);
  var stCtrl = new BMap.PanoramaControl(); //构造全景控件
  stCtrl.setOffset(new BMap.Size(100, 10));
  map.addControl(stCtrl); //添加全景控件
  map.addControl(
    new BMap.MapTypeControl({
      mapTypes: [BMAP_NORMAL_MAP, BMAP_SATELLITE_MAP, BMAP_HYBRID_MAP],
    })
  );
  // map.addEventListener("click", function (e) {
  //   console.log(e.point.lng + "," + e.point.lat);
  //   // aa.push(e.point.lng + "," + e.point.lat);
  // });
  // [
  //   "96.13017887752788,35.833468131842004",
  //   "102.82679492887074,30.38705449265531",
  // ];
  function qqMapToBMap(lng, lat) {
    if (lng == null || lng == "" || lat == null || lat == "") return [lng, lat];
    var x_pi = 3.14159265358979324;
    var x = parseFloat(lng);
    var y = parseFloat(lat);
    var z = Math.sqrt(x * x + y * y) + 0.00002 * Math.sin(y * x_pi);
    var theta = Math.atan2(y, x) + 0.000003 * Math.cos(x * x_pi);
    var lng = (z * Math.cos(theta) + 0.0065).toFixed(5);
    var lat = (z * Math.sin(theta) + 0.006).toFixed(5);
    return [lng, lat];
  }
  arrs.forEach((val) => {
    let yi = val.coords[0];
    let er = val.coords[1];
    var points = new BMap.Point(yi, er);
    console.log();
    var myIcon = new BMap.Icon(mapImg, new BMap.Size(32, 32), {
      // 指定定位位置。
      // 当标注显示在地图上时，其所指向的地理位置距离图标左上
      // 角各偏移10像素和25像素。您可以看到在本例中该位置即是
      // 图标中央下端的尖角位置。
      anchor: new BMap.Size(25, 25),
      // 设置图片偏移。
      // 当您需要从一幅较大的图片中截取某部分作为标注图标时，您
      // 需要指定大图的偏移位置，此做法与css sprites技术类似。
      imageOffset: new BMap.Size(0, -0 * 25), // 设置图片偏移
    });
    // 接口返回的门店数，信息数据
    let proName = val.attrs.name;
    let nowProObj = [];
    for (const key in proobj) {
      if (key.includes(proName)) {
        nowProObj = proobj[key];
      }
    }
    // console.log(nowProObj);
    // 创建标注对象并添加到地图
    var marker = new BMap.Marker(points, {
      icon: myIcon,
    });

    var content = `${val.attrs.name}:${nowProObj.length}家`;
    var label = new BMap.Label(content, {
      // 创建文本标注
      position: points, // 设置标注的地理位置
      offset: new BMap.Size(-30, 3), // 设置标注的偏移量
    });
    map.addOverlay(label);
    label.setStyle({
      // 设置label的样式
      // color: "rgb(100 96 84)",
      color: "#ff5a0b",
      fontSize: "8px",
      fontWeight: 500,
      padding: "1px",
      border: "none",
    });

    function markerMethod() {
      if (!val.attrs.apiNum) return;
      //点击的省份
      rightRef.value.changeRight(val.attrs.name);
      // 点击省份之后 右边模板进行变化
      fetch(`http://up.caup.net/guihuayun/json/${val.attrs.apiNum}.json`).then(
        (da) => {
          da.json().then((da) => {
            let pointArray = [];
            da.geometry.coordinates.forEach((vals) => {
              let geometry = da.geometry.type;
              if (geometry == "Polygon") {
                vals = vals.map((val) => {
                  return new BMap.Point(val[0], val[1]);
                });
              } else {
                vals = vals[0].map((val) => {
                  return new BMap.Point(val[0], val[1]);
                });
              }

              polygon = new BMap.Polygon(vals, {
                strokeColor: randomColor(),
                strokeWeight: 3,
                strokeOpacity: 0.6,
              });
              map.addOverlay(polygon);
              // var markerClusterer;

              pointArray = pointArray.concat(polygon.getPath());
              // polygon.addEventListener("click", function (e) {
              map.setViewport(pointArray); //调整视野
            });
          });
          // 该省份门店的门数
          let arrss = [];
          // setTimeout((valss) => {
          nowProObj.forEach((val) => {
            let baiduDotted = qqMapToBMap(val.lng, val.lat);
            let points = new BMap.Point(baiduDotted[0], baiduDotted[1]);
            let markets = new BMap.Marker(points);
            map.addOverlay(markets);
            arrss.push(markets);

            var opts = {
              width: 200, // 信息窗口宽度
              // height: 100, // 信息窗口高度
              title: "利郎门店", // 信息窗口标题
              // message: "这里是故宫",
              color: "#008c8c",
            };
            var infoWindow = new BMap.InfoWindow("门店名称:" + val.khmc, opts); // 创建信息窗口对象

            //         var html = [
            //           "   <div class='infoBoxContent'>",
            //           "        <div class='title'><strong>门店信息</strong></div>",
            //           "   <div class='list'>",
            //           " <ul>",
            //           " <div class='left'><img src='house3.jpg' /></div>",
            //           " <div class='left'><a target='_blank' href='http://map.baidu.com'>中海雅园南北通透四居室</a>",
            //           "   <p>4室2厅，205.00平米，3层</p>",
            //           "     </div>",
            //           "                    <div class='rmb'>760万</div>",
            //           "      </li>",
            //           "   </ul>",
            //           "  </div>",
            //           "   </div>",
            //         ];
            //         var infoBox = new BMapLib.InfoBox(map, html.join(""), {
            //           boxStyle: {
            //             background: "rgba(255,255,255,.9)"
            //         ,width: "270px"
            // ,height: "300px"
            //           },
            //           closeIconMargin: "1px 1px 0 0",
            //           enableAutoPan: true,
            //           align: INFOBOX_AT_TOP,
            //          offset:new BMap.Size(-5,40)
            //         });

            markets.addEventListener("click", function (e) {
              map.openInfoWindow(infoWindow, points); //开启信息窗口
              // infoBox.open(points);
              map.centerAndZoom(points, 15);
            });
          });

          // var markerClusterer = new BMapLib.MarkerClusterer(map, {
          //   markers: arrss,
          // });
          // window.markersTotal=[];
          // markersTotal.push(markerClusterer)
          // window.sa=()=>{
          //    markerClusterer.clearMarkers()
          // }

          // }, 100);
        }
      );

      return false;
    }
    // 把每个省份的标注的属性方法保存起来 。后面点击列表模仿点击
    val.markerMethod = markerMethod;
    marker.addEventListener("click", markerMethod);
    marker.disableMassClear();
    label.disableMassClear();

    map.addOverlay(marker);
  });
  // map.addEventListener("zoomstart", function (evt) {
  //   let a = map.getZoom();
  //   console.log("start");
  //   console.log(a);
  // });
  map.addEventListener("zoomend", function (evt) {
    let a = map.getZoom();
    // console.log("end");

    console.log(a);
    if (a < 6) {
      map.clearOverlays();
    }
  });
  // window.onwheel = function () {
  //   let a = map.getZoom();
  //   // console.log(a);
  //   // 7的话删除所有~
  //   if (a <= 6) {
  //     map.clearOverlays();
  //   }
  // };
  // map.onstatuschanged = function (e) {
  //   console.log(e.zoom);
  // };
  maps = () => {
    return map;
  };
};
getHomeDatas().then((da) => {
  data = da.data.data;
  let rightDatas = [
    // {
    //   proName: "福建省",
    //   cityData: [
    //     {
    //       cityName: "莆田市",
    //       countryDatas: [
    //         {
    //           mdmc: "mdmc",
    //           sskhmc: "sskhmc",
    //         }
    //       ]
    //     }
    //   ]
    // }
  ];

  data.forEach((val) => {
    if (val.jmpro.length == 2 && val.jmpro != "缅甸") {
      val.jmpro = val.jmpro + "省";
      // if(val.jmpro)
    }
    let isHave = rightDatas.findIndex((valss) => {
      return valss.proName.includes(val.jmpro);
    });
    if (isHave >= 0) {
      let cityStateIndex = rightDatas[isHave].cityData.findIndex((res) => {
        return res.cityName == val.jmcity;
      });
      if (cityStateIndex >= 0) {
        rightDatas[isHave].cityData[cityStateIndex].countryDatas.push({
          mdmc: val.mdmc,
          sskhmc: val.sskhmc,
          lng: val.lng,
          lat: val.lat,
        });
      } else {
        rightDatas[isHave].cityData.push({
          cityName: val.jmcity,
          countryDatas: [
            {
              mdmc: val.mdmc,
              sskhmc: val.sskhmc,
              lng: val.lng,
              lat: val.lat,
            },
          ],
        });
      }
    } else {
      rightDatas.push({
        proName: val.jmpro,
        cityData: [
          {
            cityName: val.jmcity,
            countryDatas: [
              {
                mdmc: val.mdmc,
                sskhmc: val.sskhmc,
                lng: val.lng,
                lat: val.lat,
              },
            ],
          },
        ],
      });
    }
    let { lng, lat, khmc, khflmc } = val;
    if (proobj[val.jmpro]) {
      proobj[val.jmpro].push({
        lng,
        lat,
        khmc,
        khflmc,
      });
    } else {
      proobj[val.jmpro] = [
        {
          lng,
          lat,
          khmc,
          khflmc,
        },
      ];
    }
  });
  // console.log(rightDatas);
  homeData.value = rightDatas;
  mapInt();
});

const cityClickExpand = (val) => {
  expandContent(val);
};
onMounted((val) => {
  // mapInt();
});
</script>

<template>
  <div class="contains">
    <div id="allmap"></div>
    <!-- <div class="right-content"> -->
    <right-content
      :homeData="homeData"
      :changePro="changePro"
      ref="rightRef"
      @expandContent="expandContent"
      @changeMap="changeMap"
      @cityClickExpand="cityClickExpand"
    ></right-content>
    <!-- </div> -->
  </div>
</template>

<style lang="less">
html,
body {
  width: 100%;
  height: 100%;
  overflow: hidden;
  user-select: none;
}
.contains {
  position: relative;
  #allmap {
    height: 100%;
    width: 100%;
    path {
      fill-opacity: 0.2;
    }

    position: relative;
    .BMap_bubble_title {
      color: #cc5522;
    }

    .BMap_cpyCtrl {
      display: none;
    }

    .anchorBL {
      display: none;
    }
  }
  .right-content {
    width: 100%;
    // position: relative;
    // box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.08);
  }
}
#app {
  /* border: 1px solid red; */
  width: 100%;
  height: 100%;
  overflow: hidden;
  .contains {
    height: 100%;
    // border: 1px solid red;
    box-sizing: border-box;
  }
}

body,
html {
  width: 100%;
  height: 100%;
  margin: 0;
  font-family: "微软雅黑";
}

#r-result {
  width: 100%;
}
</style>
